name: Publish Package

on:
  push:
    branches:
      - main
    paths-ignore:
      - '_docs/**'
      - '*.md'
      - '*.editorconfig'
      - '*.gitignore'

jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [ 12.x ]
        os: [ ubuntu-18.04 ]
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Authenticate with Registry
        run: |
          yarn logout
          echo "@apollo-elements:registry=http://registry.npmjs.org/" > .npmrc
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish package
        run: |
          npm install
          npm install --g lerna
          lerna publish --npm-tag=latest --yes --message "chore: release new versions"
